import {PropsWithChildren} from "react";
import Head from "next/head";
import styles from '../styles/Home.module.scss'
import Header from "./game_page/Header/Header";
import {createTheme} from "@mui/material/styles";
import {ThemeProvider} from "@mui/material";
import Footer from "./Footer/Footer";


const Layout = ({children}: PropsWithChildren<{}>) => {
    const darkTheme = createTheme({
        components: {
            // Name of the component
        },
        palette: {
            mode: 'dark',
            primary: {
                light: '#757ce8',
                main: '#b2b0b0',
                dark: '#171717',
                contrastText: '#545454',
            },
            secondary: {
                light: '#ff7961',
                main: '#f44336',
                dark: '#ba000d',
                contrastText: '#000',
            },
        },
    });

    return (
        <ThemeProvider theme={darkTheme}>
            <Head>
                <title>Next.js title</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <main className={styles.main}>{children}
                <div className={styles.description}>
                </div>
            </main>
            <Footer/>
        </ThemeProvider>
    )


};

export default Layout;